# Generated by Django 5.0.1 on 2024-01-28 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealBankCashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='TCB', max_length=20, verbose_name='Tài khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nộp tiền')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sao kê tiền TKNH',
                'verbose_name_plural': 'Sao kê tiền TKNH',
            },
        ),
        migrations.CreateModel(
            name='RealStockAccountCashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='011C263979', max_length=20, verbose_name='Tài khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nộp tiền')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sao kê tiền TKCK',
                'verbose_name_plural': 'Sao kê tiền TKCK',
            },
        ),
        migrations.CreateModel(
            name='RealTradingPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='011C263979', max_length=20, verbose_name='Tài khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày')),
                ('max_amount', models.FloatField(verbose_name='Sức mua tối đa')),
                ('min_amount', models.FloatField(verbose_name='Sức mua tối thiểu')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sức mua tài khoản',
                'verbose_name_plural': 'Sức mua tài khoản',
            },
        ),
    ]
