# Generated by Django 4.1.5 on 2024-01-11 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('description', models.TextField(max_length=255, verbose_name='Mô tả')),
                ('parameters', models.FloatField(verbose_name='Tham số quy định')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Regulatio_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Quy định Kho',
                'verbose_name_plural': 'Quy định kho',
            },
        ),
    ]
