# Generated by Django 5.0.1 on 2024-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateNotTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ngày lễ không giao dịch',
                'verbose_name_plural': 'Ngày lễ không giao dịch',
            },
        ),
        migrations.CreateModel(
            name='DividendManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'cash'), ('stock', 'stock'), ('option', 'option'), ('order', 'order')], max_length=20)),
                ('date_apply', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('cash', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('price_option', models.FloatField(default=0)),
                ('stock_option', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Quản lí cổ tức',
                'verbose_name_plural': 'Quản lí cổ tức',
            },
        ),
        migrations.CreateModel(
            name='StockPriceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Giá thị trường',
                'verbose_name_plural': 'Giá thị trường',
            },
        ),
    ]
