# Generated by Django 4.1.5 on 2023-12-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'cash'), ('stock', 'stock'), ('option', 'option'), ('order', 'order')], max_length=20)),
                ('date_apply', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('cash', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('price_option', models.FloatField(default=0)),
                ('stock_option', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
