# Generated by Django 5.0.1 on 2024-01-27 15:53

import django.db.models.deletion
import django.utils.timezone
import operation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpd', '0002_alter_clientpartnerinfo_commission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('interest_fee', models.FloatField(default=operation.models.get_interest_fee_default, verbose_name='Lãi suất')),
                ('transaction_fee', models.FloatField(default=operation.models.get_transaction_fee_default, verbose_name='Phí giao dịch')),
                ('tax', models.FloatField(default=operation.models.get_tax_fee_default, verbose_name='Thuế')),
                ('net_cash_flow', models.FloatField(default=0, verbose_name='Nạp rút tiền ròng')),
                ('net_trading_value', models.FloatField(default=0, verbose_name='Giao dịch ròng')),
                ('cash_balance', models.FloatField(default=0, verbose_name='Số dư tiền')),
                ('market_value', models.FloatField(default=0, verbose_name='Giá trị thị trường')),
                ('nav', models.FloatField(default=0, verbose_name='Tài sản ròng')),
                ('initial_margin_requirement', models.FloatField(default=0, verbose_name='Kí quy ban đầu')),
                ('margin_ratio', models.FloatField(default=0, verbose_name='Tỷ lệ margin')),
                ('excess_equity', models.FloatField(default=0, verbose_name='Dư kí quỹ')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('total_buy_trading_value', models.FloatField(default=0, verbose_name='Tổng giá trị mua')),
                ('cash_t1', models.FloatField(default=0, verbose_name='Số dư tiền T1')),
                ('cash_t2', models.FloatField(default=0, verbose_name='Số dư tiền T2')),
                ('cash_t0', models.FloatField(default=0, verbose_name='Số dư tiền bán đã về')),
                ('interest_cash_balance', models.FloatField(default=0, verbose_name='Số dư tiền tính lãi')),
                ('total_loan_interest', models.FloatField(default=0, verbose_name='Tổng lãi vay')),
                ('total_interest_paid', models.FloatField(default=0, verbose_name='Tổng lãi vay đã trả')),
                ('total_temporarily_interest', models.FloatField(default=0, verbose_name='Tổng lãi vay tạm tính')),
                ('total_pl', models.FloatField(default=0, verbose_name='Tổng lời lỗ')),
                ('total_closed_pl', models.FloatField(default=0, verbose_name='Tổng lời lỗ đã chốt')),
                ('total_temporarily_pl', models.FloatField(default=0, verbose_name='Tổng lời lỗ tạm tính')),
                ('credit_limit', models.FloatField(default=operation.models.get_credit_limit_default, verbose_name='Hạn mức mua')),
                ('milestone_date_lated', models.DateTimeField(blank=True, null=True, verbose_name='Ngày tất toán gần nhất')),
                ('cpd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpd.clientpartnerinfo', verbose_name='Người giới thiệu')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
            },
        ),
        migrations.CreateModel(
            name='MaxTradingPowerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Quản lí sức mua',
                'verbose_name_plural': 'Quản lí sức mua',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operation.account',),
        ),
        migrations.CreateModel(
            name='AccountMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.IntegerField(verbose_name='Giai đoạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('interest_fee', models.FloatField(default=0.16, verbose_name='Lãi suất')),
                ('transaction_fee', models.FloatField(default=0.0015, verbose_name='Phí giao dịch')),
                ('tax', models.FloatField(default=0.0001, verbose_name='Thuế')),
                ('net_cash_flow', models.FloatField(default=0, verbose_name='Nạp rút tiền ròng')),
                ('total_buy_trading_value', models.FloatField(default=0, verbose_name='Tổng giá trị mua')),
                ('net_trading_value', models.FloatField(default=0, verbose_name='Giao dịch ròng')),
                ('interest_paid', models.FloatField(default=0, verbose_name='Tổng lãi vay đã trả')),
                ('closed_pl', models.FloatField(default=0, verbose_name='Tổng lời lỗ đã chốt')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.account', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Mốc Tài khoản',
                'verbose_name_plural': 'Mốc Tài khoản',
            },
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nộp tiền')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.account', verbose_name='Tài khoản')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Giao dịch tiền',
                'verbose_name_plural': 'Giao dịch tiền',
            },
        ),
        migrations.CreateModel(
            name='ExpenseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('type', models.CharField(choices=[('interest', 'Lãi vay'), ('transaction_fee', 'Phí giao dịch'), ('tax', 'Thuế bán')], max_length=50, verbose_name='Loại phí')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diễn giải')),
                ('interest_cash_balance', models.FloatField(blank=True, null=True, verbose_name='Số dư tiền tính lãi')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.account', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Bảng kê chi phí ',
                'verbose_name_plural': 'Bảng kê chi phí ',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('stock', models.CharField(max_length=10, verbose_name='Cổ phiếu')),
                ('avg_price', models.FloatField(default=0, verbose_name='Giá')),
                ('on_hold', models.IntegerField(blank=True, default=0, null=True, verbose_name='Khả dụng')),
                ('receiving_t2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Chờ về T2')),
                ('receiving_t1', models.IntegerField(blank=True, default=0, null=True, verbose_name='Chờ về T1')),
                ('cash_divident', models.FloatField(blank=True, default=0, null=True, verbose_name='Cổ tức bằng tiền')),
                ('stock_divident', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cổ tức cổ phiếu')),
                ('market_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Giá thị trường')),
                ('profit', models.FloatField(blank=True, default=0, null=True, verbose_name='Lợi nhuận')),
                ('percent_profit', models.FloatField(blank=True, default=0, null=True, verbose_name='%Lợi nhuận')),
                ('sum_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tổng cổ phiếu')),
                ('market_value', models.FloatField(blank=True, default=0, null=True, verbose_name='Giá trị thị trường')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.account', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Danh mục ',
                'verbose_name_plural': 'Danh mục ',
            },
        ),
        migrations.CreateModel(
            name='StockListMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('stock', models.CharField(max_length=8, verbose_name='Cổ phiếu')),
                ('initial_margin_requirement', models.FloatField(verbose_name='Kí quy ban đầu')),
                ('ranking', models.IntegerField(verbose_name='Loại')),
                ('exchanges', models.CharField(max_length=10, verbose_name='Sàn giao dịch')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Danh mục cho vay',
                'verbose_name_plural': 'Danh mục cho vay',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('position', models.CharField(choices=[('buy', 'Mua'), ('sell', 'Bán')], max_length=4, verbose_name='Mua/Bán')),
                ('price', models.FloatField(verbose_name='Giá')),
                ('qty', models.IntegerField(verbose_name='Khối lượng')),
                ('transaction_fee', models.FloatField(verbose_name='Phí giao dịch')),
                ('tax', models.FloatField(default=0, verbose_name='Thuế')),
                ('total_value', models.FloatField(default=0, verbose_name='Giá trị giao dịch')),
                ('net_total_value', models.FloatField(default=0, verbose_name='Giá trị giao dịch ròng')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.account', verbose_name='Tài khoản')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.stocklistmargin', verbose_name='Cổ phiếu')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sổ lệnh ',
                'verbose_name_plural': 'Sổ lệnh ',
            },
        ),
    ]
