# Generated by Django 4.1.5 on 2023-12-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='market_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Giá trị thị trường'),
        ),
    ]
